basePath: /
definitions:
  models.Country:
    properties:
      code2:
        description: Code2 holds the value of the "code2" field.
        type: string
      gnp:
        description: Gnp holds the value of the "gnp" field.
        type: number
      gnp_old:
        description: GnpOld holds the value of the "gnp_old" field.
        type: number
      government_form:
        description: GovernmentForm holds the value of the "government_form" field.
        type: string
      head_of_state:
        description: HeadOfState holds the value of the "head_of_state" field.
        type: string
      id:
        description: ID of the ent.
        type: string
      indep_year:
        description: IndepYear holds the value of the "indep_year" field.
        type: integer
      life_expectancy:
        description: LifeExpectancy holds the value of the "life_expectancy" field.
        type: number
      local_name:
        description: LocalName holds the value of the "local_name" field.
        type: string
      name:
        description: Name holds the value of the "name" field.
        type: string
      population:
        description: Population holds the value of the "population" field.
        type: integer
      region:
        description: Region holds the value of the "region" field.
        type: string
      surface_area:
        description: SurfaceArea holds the value of the "surface_area" field.
        type: number
    type: object
host: localhost:9090
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a server that gives information about countries
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /countries:
    get:
      consumes:
      - application/json
      description: get all details
      operationId: get-countries-details
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Country'
            type: array
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get all countries details
  /countries/{id}:
    get:
      consumes:
      - application/json
      description: get all details
      operationId: get-country-details
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Country'
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get country details
    put:
      consumes:
      - application/json
      description: Update country
      operationId: update-country-details
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Country'
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Update country based on parameter
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
