// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// City is the predicate function for city builders.
type City func(*sql.Selector)

// Country is the predicate function for country builders.
type Country func(*sql.Selector)

// Country_language is the predicate function for country_language builders.
type Country_language func(*sql.Selector)
